package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, LEAVE, PING, PONG, BUDDY_PING, BUDDY_PONG, REQUEST_MUTEX, TOKEN_MUTEX,
	PUT_FILE, REMOVE_FILE, FOLLOW_REQUEST, LIST_FILES_REQUEST, LIST_FILES_RESPONSE,
	BACKUP_FILE
}
